# Generated by Django 3.1.4 on 2020-12-23 11:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201223_0938'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_user_not_equal',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, following=django.db.models.expressions.F('user')), name='following_user_not_equal'),
        ),
    ]
